# Generated by Django 3.0.5 on 2021-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='parser',
            field=models.TextField(null=True),
        ),
    ]
