# Generated by Django 3.0.5 on 2021-08-08 12:54

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_parser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='batteryLevel',
        ),
        migrations.RemoveField(
            model_name='data',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='data',
            name='luminosity',
        ),
        migrations.RemoveField(
            model_name='data',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='data',
            name='temp',
        ),
        migrations.AddField(
            model_name='data',
            name='data',
            field=djongo.models.fields.JSONField(null=True),
        ),
    ]
