const AuthTypes = {
	USER_LOADING: 'USER_LOADING',
	USER_LOADED: 'USER_LOADED',
	LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
	LOGIN_FAILED: 'LOGIN_FAILED',
	LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL',
	AUTHENTIFICATION_ERROR: 'AUTHENTIFICATION_ERROR',
	REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST',
	REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
};

export default AuthTypes;