# Generated by Django 3.1.1 on 2020-09-20 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('deviceId', models.CharField(max_length=10, unique=True)),
                ('firmware', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawData', models.CharField(max_length=24)),
                ('temp', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('humidity', models.PositiveSmallIntegerField(default=0)),
                ('pressure', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('luminosity', models.PositiveSmallIntegerField(default=0)),
                ('batteryLevel', models.PositiveSmallIntegerField(default=0)),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device', to_field='deviceId')),
            ],
        ),
    ]
