# Generated by Django 3.1.1 on 2020-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
